"""
Poisoning Attack Strategies for OLH
=====================================
Three attack strategies targeting the OLH (Optimized Local Hashing) protocol.

In OLH, each report is a tuple (sanitized_value, rnd_seed) where:
  - rnd_seed identifies a hash function h: [d] → [g].
  - sanitized_value ∈ [0, g-1] is the GRR-perturbed hash of the true value.

An item v is "supported" by report (y, seed) if h_seed(v) == y. The adversary
crafts (y, seed) pairs to strategically support effective attack items without
supporting any target items (to avoid directly "helping" items in a detectable
way while still manipulating ranking).

  1. Random Attack  — Fake users report a target item via LH_Client.
  2. ROA            — Random Output Attack: uses random (y, seed) pairs
                      that support only non-target items.
  3. Greedy Attack  — Selects (seed, y) combinations minimizing cost, where
                      cost is inversely proportional to how many effective
                      attack items the combination supports.
"""

import numpy as np
import random
from sys import maxsize
from typing import Dict, List, Optional, Tuple
import xxhash

from ..core.olh import LH_Client
from functools import lru_cache

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------
class HashCache:
    """哈希值预计算缓存"""

    def __init__(self, g):
        self.g = g
        self._cache = {}

    @lru_cache(maxsize=10000)
    def get_hash(self, value, seed):
        """缓存哈希计算结果"""
        return xxhash.xxh32(str(value), seed=seed).intdigest() % self.g

def _g(epsilon: float) -> int:
    return int(round(np.exp(epsilon))) + 1


def _hash(value: int, seed: int, g: int) -> int:
    return xxhash.xxh32(str(value), seed=seed).intdigest() % g


def _effective_items(A, T, freq):
    return [a for a in A if any(freq[t] > freq[a] for t in T)]


def _calculate_costs(
    target_items: List[int],
    eff_items: List[int],
    freq: Dict[int, int],
    hash_funcs: List[int],
    g: int,
) -> Tuple[Optional[int], Optional[int]]:
    """
    Find the (seed, hashed_value) pair that minimizes attack cost.

    Cost is defined as 1 / sum(1 / dist(a, nearest_target)) over all effective
    attack items supported by (seed, hashed_value). Lower cost = higher impact.

    Only (seed, y) pairs that do NOT support any target item are considered,
    ensuring the fake reports do not inadvertently inflate target items.

    Args:
        target_items: Target item IDs.
        eff_items: Effective attack item IDs.
        freq: Current frequency estimates.
        hash_funcs: List of random seeds (hash function identifiers).
        g: Hash output domain size.

    Returns:
        Tuple of (best_seed, best_hashed_value) or (None, None) if no valid pair.
    """
    cache = HashCache(g)
    min_cost = float("inf")
    best_seed, best_y = None, None

    for seed in hash_funcs:
        for y in range(g):
            # Skip if this (seed, y) supports any target item
            if any(cache.get_hash(t, seed) == y for t in target_items):
                continue

            # Compute support score for effective attack items
            score = 0.0
            for a in eff_items:
                if cache.get_hash(a, seed) == y:
                    dists = [freq[t] - freq[a] for t in target_items if freq[t] > freq[a]]
                    if dists:
                        score += 1.0 / min(dists)

            if score > 0:
                cost = 1.0 / score
                if cost < min_cost:
                    min_cost = cost
                    best_seed = seed
                    best_y = y

    return best_seed, best_y


# ---------------------------------------------------------------------------
# Public Attack APIs
# ---------------------------------------------------------------------------

def random_attack_olh(
    n2: int,
    target_items: List[int],
    d: int,
    epsilon: float,
) -> List[Tuple[int, int]]:
    """
    Random Attack for OLH.

    Each fake user selects a target item uniformly at random and submits a
    report generated by LH_Client as if they were an honest user with that
    value. This directly inflates target item support.

    Args:
        n2: Number of fake users.
        target_items: List of target item IDs.
        d: Domain size.
        epsilon: Privacy budget.

    Returns:
        List of n2 (sanitized_value, rnd_seed) tuples.

    Example:
        >>> fake = random_attack_olh(n2=500, target_items=[2,5], d=100, epsilon=2.0)
    """
    fake_data = []
    for _ in range(n2):
        chosen = int(np.random.choice(target_items))
        fake_data.append(LH_Client(chosen, d, epsilon))
    return fake_data


def roa_attack_olh(
    n2: int,
    non_target_items: List[int],
    d: int,
    epsilon: float,
) -> List[Tuple[int, int]]:
    """
    Random Output Attack (ROA) for OLH.

    Each fake user generates a random seed and reports the hash of a randomly
    selected non-target item under that seed. The resulting (y, seed) pair
    supports only non-target items, serving as a noise baseline.

    Args:
        n2: Number of fake users.
        non_target_items: List of non-target item IDs.
        d: Domain size.
        epsilon: Privacy budget.

    Returns:
        List of n2 (sanitized_value, rnd_seed) tuples.

    Example:
        >>> fake = roa_attack_olh(n2=500, non_target_items=[0,1,3,...],
        ...     d=100, epsilon=2.0)
    """
    g = _g(epsilon)
    fake_data = []
    for _ in range(n2):
        seed = np.random.randint(0, maxsize, dtype=np.int64)
        chosen = int(np.random.choice(non_target_items))
        y = _hash(chosen, seed, g)
        fake_data.append((y, seed))
    return fake_data


def greedy_attack_olh(
    n2: int,
    target_items: List[int],
    non_target_items: List[int],
    expected_perturbed_freq: Dict[int, int],
    d: int,
    epsilon: float,
    hash_funcs: Optional[List[int]] = None,
    num_hash_funcs: int = 100,
) -> List[Tuple[int, int]]:
    """
    Greedy Attack for OLH.

    At each step, finds the (seed, y) pair with the lowest cost (highest
    combined impact on effective attack items) and injects enough fake users
    to push the most cost-effective item above its nearest target.

    The trick: only pairs that do NOT hash any target item to y are considered.
    This means fake votes for non-targets don't accidentally boost targets, and
    the attack avoids a statistical signature that could be detected by the
    server comparing target item support patterns.

    Args:
        n2: Number of fake users.
        target_items: Target item IDs (T).
        non_target_items: Non-target item IDs (A).
        expected_perturbed_freq: Expected perturbed frequency estimates.
        d: Domain size.
        epsilon: Privacy budget.
        hash_funcs: Pre-generated random seeds to use as hash functions.
                    If None, generates `num_hash_funcs` random seeds.
        num_hash_funcs: Number of random hash functions to sample (default 100).

    Returns:
        List of (sanitized_value, rnd_seed) tuples.

    Example:
        >>> fake = greedy_attack_olh(n2=500, target_items=[2,5],
        ...     non_target_items=list(range(100)), expected_perturbed_freq=epf,
        ...     d=100, epsilon=2.0)
    """
    g = _g(epsilon)

    if hash_funcs is None:
        hash_funcs = [
            int(np.random.randint(0, maxsize, dtype=np.int64))
            for _ in range(num_hash_funcs)
        ]

    attacked_freq = expected_perturbed_freq.copy()
    fake_data = []
    optimal_combinations = []
    eff_items = _effective_items(non_target_items, target_items, attacked_freq)

    while n2 > 0 and eff_items:
        best_seed, best_y = _calculate_costs(
            target_items, eff_items, attacked_freq, hash_funcs, g
        )
        if best_seed is None:
            break

        optimal_combinations.append((best_y, best_seed))

        # Find the effective attack item with minimum distance supported by this hash
        min_diff = float("inf")
        min_diff_item = None
        for a in eff_items:
            if _hash(a, best_seed, g) == best_y:
                dists = [attacked_freq[t] - attacked_freq[a] for t in target_items if attacked_freq[t] > attacked_freq[a]]
                diff = min(dists, default=float("inf"))
                if diff < min_diff:
                    min_diff = diff
                    min_diff_item = a

        if min_diff_item is None or min_diff == float("inf"):
            break

        steps = min(int(min_diff), n2)
        fake_data.extend([(best_y, best_seed)] * steps)

        # Update frequencies for all supported items
        for a in eff_items:
            if _hash(a, best_seed, g) == best_y:
                attacked_freq[a] += steps
        for t in target_items:
            if _hash(t, best_seed, g) == best_y:
                attacked_freq[t] += steps

        n2 -= steps
        eff_items = _effective_items(non_target_items, target_items, attacked_freq)

    if n2 > 0 and optimal_combinations:
        extra = random.choices(optimal_combinations, k=n2)
        fake_data.extend(extra)
    elif n2 > 0:
        fake_data.extend(roa_attack_olh(n2, non_target_items, d, epsilon))

    return fake_data
